--!strict
-- MusicCatalog.generated.lua
--
-- GENERATED FILE - DO NOT EDIT BY HAND.
-- Source of truth: the CSV catalog under music/ (see docs/music.md).
-- Regenerate with:
--   python3 tools/compile_music_catalog.py --mode development
--
-- Runtime fields only. Local paths, hashes, license evidence, archive names, and
-- production notes stay in the CSVs.

return {
	formatVersion = 1,
	mode = "development",
	experienceId = "CLICKGAME",
	inputDigest = "26d800260d0519f438e4f5075734b0d3cda7cd50bcb0245b7498b532ba979e2d",
	credits = {},
	collections = {},
	tracks = {},
	trackIndex = {},
	pools = {
		{
			id = "COMMERCE",
			displayName = "Commerce",
			unlockRule = "CommerceFloor",
			targetCount = 8,
			selectionPolicy = "ShuffledBagWithUnlockBoost",
			entries = {},
		},
		{
			id = "EARLY_GAME",
			displayName = "Early Game",
			unlockRule = "Always",
			targetCount = 8,
			selectionPolicy = "ShuffledBag",
			entries = {},
		},
		{
			id = "INDUSTRY",
			displayName = "Industry",
			unlockRule = "IndustryFloor",
			targetCount = 8,
			selectionPolicy = "ShuffledBagWithUnlockBoost",
			entries = {},
		},
		{
			id = "RECOVERY",
			displayName = "Recovery",
			unlockRule = "ContextualOnly",
			targetCount = 6,
			selectionPolicy = "WeightedContextual",
			entries = {},
		},
		{
			id = "SCIENCE",
			displayName = "Science",
			unlockRule = "ScienceFloor",
			targetCount = 8,
			selectionPolicy = "ShuffledBagWithUnlockBoost",
			entries = {},
		},
		{
			id = "UNIVERSAL",
			displayName = "Universal",
			unlockRule = "Always",
			targetCount = 8,
			selectionPolicy = "ShuffledBag",
			entries = {},
		},
	},
	cues = {
		{
			id = "CORE_EMERGENCE",
			cueClass = "Cinematic",
			priority = 100,
			loopMode = "LoopIfNeeded",
			crossfadeSeconds = 2,
			fallbackPoolId = "RECOVERY",
			storyMomentsControlled = true,
			assignments = {},
		},
		{
			id = "FLOOR_COMMERCE_UNLOCK",
			cueClass = "MajorMilestone",
			priority = 80,
			loopMode = "NoLoop",
			crossfadeSeconds = 1.5,
			fallbackPoolId = "COMMERCE",
			storyMomentsControlled = true,
			assignments = {},
		},
		{
			id = "FLOOR_INDUSTRY_UNLOCK",
			cueClass = "MajorMilestone",
			priority = 80,
			loopMode = "NoLoop",
			crossfadeSeconds = 1.5,
			fallbackPoolId = "INDUSTRY",
			storyMomentsControlled = true,
			assignments = {},
		},
		{
			id = "FLOOR_SCIENCE_UNLOCK",
			cueClass = "MajorMilestone",
			priority = 80,
			loopMode = "NoLoop",
			crossfadeSeconds = 1.5,
			fallbackPoolId = "SCIENCE",
			storyMomentsControlled = true,
			assignments = {},
		},
		{
			id = "GOOB_LORE",
			cueClass = "Cinematic",
			priority = 100,
			loopMode = "LoopIfNeeded",
			crossfadeSeconds = 3,
			fallbackPoolId = "EARLY_GAME",
			storyMomentsControlled = true,
			assignments = {},
		},
		{
			id = "GOO_REVEAL",
			cueClass = "Cinematic",
			priority = 100,
			loopMode = "NoLoop",
			crossfadeSeconds = 2.5,
			fallbackPoolId = "EARLY_GAME",
			storyMomentsControlled = true,
			assignments = {},
		},
		{
			id = "INTRO_DESCENT",
			cueClass = "Cinematic",
			priority = 100,
			loopMode = "NoLoop",
			crossfadeSeconds = 1.5,
			fallbackPoolId = "EARLY_GAME",
			storyMomentsControlled = true,
			assignments = {},
		},
		{
			id = "INTRO_ORBIT",
			cueClass = "Cinematic",
			priority = 100,
			loopMode = "Loop",
			crossfadeSeconds = 2.5,
			fallbackPoolId = "UNIVERSAL",
			storyMomentsControlled = true,
			assignments = {},
		},
		{
			id = "OLD_GOO_BACKSTORY",
			cueClass = "Cinematic",
			priority = 100,
			loopMode = "LoopIfNeeded",
			crossfadeSeconds = 3.5,
			fallbackPoolId = "RECOVERY",
			storyMomentsControlled = true,
			assignments = {},
		},
		{
			id = "OPENING_ARC_COMPLETE",
			cueClass = "MajorMilestone",
			priority = 70,
			loopMode = "NoLoop",
			crossfadeSeconds = 1.5,
			fallbackPoolId = "EARLY_GAME",
			storyMomentsControlled = true,
			assignments = {},
		},
		{
			id = "QUEST_COMPLETE_STINGER",
			cueClass = "Stinger",
			priority = 30,
			loopMode = "NoLoop",
			crossfadeSeconds = 0.2,
			fallbackPoolId = "UNIVERSAL",
			storyMomentsControlled = false,
			assignments = {},
		},
		{
			id = "REBIRTH_FINALE",
			cueClass = "Cinematic",
			priority = 100,
			loopMode = "NoLoop",
			crossfadeSeconds = 2,
			fallbackPoolId = "UNIVERSAL",
			storyMomentsControlled = true,
			assignments = {},
		},
	},
}
