local ServerScriptService = game:GetService("ServerScriptService")

local Services = ServerScriptService:WaitForChild("Services")

local PlayerDataService = require(Services:WaitForChild("PlayerDataService"))
local SheetService = require(Services:WaitForChild("SheetService"))
local CookieService = require(Services:WaitForChild("CookieService"))
local ShieldService = require(Services:WaitForChild("ShieldService"))
local UpgradeService = require(Services:WaitForChild("UpgradeService"))
local ProductionService = require(Services:WaitForChild("ProductionService"))
local AutoclickService = require(Services:WaitForChild("AutoclickService"))
local ResetStatsService = require(Services:WaitForChild("ResetStatsService"))
local GoldenCookieService = require(Services:WaitForChild("GoldenCookieService"))
local GemService = require(Services:WaitForChild("GemService"))
local BoostShopService = require(Services:WaitForChild("BoostShopService"))
local BoostFieldService = require(Services:WaitForChild("BoostFieldService"))
local WheelService = require(Services:WaitForChild("WheelService"))
local DailyRewardService = require(Services:WaitForChild("DailyRewardService"))
local OfflineEarningsService = require(Services:WaitForChild("OfflineEarningsService"))
local PlayerSetupService = require(Services:WaitForChild("PlayerSetupService"))
local TestCommandService = require(Services:WaitForChild("TestCommandService"))
local PvpService = require(Services:WaitForChild("PvpService"))
local MascotService = require(Services:WaitForChild("MascotService"))
local StoryService = require(Services:WaitForChild("StoryService"))
local XpService = require(Services:WaitForChild("XpService"))
local TitleService = require(Services:WaitForChild("TitleService"))
local BoostService = require(Services:WaitForChild("BoostService"))
local MonetizationService = require(Services:WaitForChild("MonetizationService"))
local PlayerMetricsService = require(Services:WaitForChild("PlayerMetricsService"))
local SettingsService = require(Services:WaitForChild("SettingsService"))
local MusicService = require(Services:WaitForChild("MusicService"))
local DevTuningService = require(Services:WaitForChild("DevTuningService"))
local OrbLayerPreviewService = require(Services:WaitForChild("OrbLayerPreviewService"))
local PlacementAnalyticsService = require(Services:WaitForChild("PlacementAnalyticsService"))
local AutoclickerAnalyticsService = require(Services:WaitForChild("AutoclickerAnalyticsService"))
local FloorAnalyticsService = require(Services:WaitForChild("FloorAnalyticsService"))
local FloorService = require(Services:WaitForChild("FloorService"))
local QuestAnalyticsService = require(Services:WaitForChild("QuestAnalyticsService"))
local BoostAnalyticsService = require(Services:WaitForChild("BoostAnalyticsService"))
local FriendBoostAnalyticsService = require(Services:WaitForChild("FriendBoostAnalyticsService"))
local FriendBoostService = require(Services:WaitForChild("FriendBoostService"))
local HubCoreAnalyticsService = require(Services:WaitForChild("HubCoreAnalyticsService"))
local QuestService = require(Services:WaitForChild("QuestService"))
local HubCoreService = require(Services:WaitForChild("HubCoreService"))
local GlobalLeaderboardService = require(Services:WaitForChild("GlobalLeaderboardService"))

-- Apply the PVP pause (hide StarterPack weapons) before any player spawns.
PvpService.Init()
DevTuningService.Init()
OrbLayerPreviewService.Init()
PlacementAnalyticsService.Init()
AutoclickerAnalyticsService.Init()
FloorAnalyticsService.Init()
QuestAnalyticsService.Init()
BoostAnalyticsService.Init()
FriendBoostAnalyticsService.Init()
HubCoreAnalyticsService.Init()

PlayerDataService.Init()
SheetService.Init()
FloorService.Init()
CookieService.Init()
ShieldService.Init()
UpgradeService.Init()
-- Before ProductionService, which registers its CpS refresh on this service's change signal.
FriendBoostService.Init()
ProductionService.Init()
AutoclickService.Init()
ResetStatsService.Init()
GoldenCookieService.Init()
GemService.Init()
BoostShopService.Init()
BoostFieldService.Init()
WheelService.Init()
DailyRewardService.Init()
OfflineEarningsService.Init()
StoryService.Init()
QuestService.Init()
HubCoreService.Init()
XpService.Init()
TitleService.Init()
PlayerMetricsService.Init()
SettingsService.Init()
-- Before PlayerSetupService, so a player already in the server finds the Orbit
-- Radio channels the moment their setup reconciles Persistent.Music.
MusicService.Init()
GlobalLeaderboardService.Init()
PlayerSetupService.Init()
TestCommandService.Init()
MascotService.Init()
BoostService.Init()
MonetizationService.Init()

print("Cosmic Crumb server started")
