local ServerScriptService = game:GetService("ServerScriptService")

local Services = ServerScriptService:WaitForChild("Services")

local PlayerDataService = require(Services:WaitForChild("PlayerDataService"))
local SheetService = require(Services:WaitForChild("SheetService"))
local CookieService = require(Services:WaitForChild("CookieService"))
local ShieldService = require(Services:WaitForChild("ShieldService"))
local UpgradeService = require(Services:WaitForChild("UpgradeService"))
local ProductionService = require(Services:WaitForChild("ProductionService"))
local AutoclickService = require(Services:WaitForChild("AutoclickService"))
local ResetStatsService = require(Services:WaitForChild("ResetStatsService"))
local GoldenCookieService = require(Services:WaitForChild("GoldenCookieService"))
local GemService = require(Services:WaitForChild("GemService"))
local WheelService = require(Services:WaitForChild("WheelService"))
local DailyRewardService = require(Services:WaitForChild("DailyRewardService"))
local OfflineEarningsService = require(Services:WaitForChild("OfflineEarningsService"))
local PlayerSetupService = require(Services:WaitForChild("PlayerSetupService"))
local TestCommandService = require(Services:WaitForChild("TestCommandService"))
local PvpService = require(Services:WaitForChild("PvpService"))
local MascotService = require(Services:WaitForChild("MascotService"))
local StoryService = require(Services:WaitForChild("StoryService"))
local XpService = require(Services:WaitForChild("XpService"))
local BoostService = require(Services:WaitForChild("BoostService"))
local MonetizationService = require(Services:WaitForChild("MonetizationService"))
local PlayerMetricsService = require(Services:WaitForChild("PlayerMetricsService"))
local SettingsService = require(Services:WaitForChild("SettingsService"))
local DevTuningService = require(Services:WaitForChild("DevTuningService"))
local PlacementAnalyticsService = require(Services:WaitForChild("PlacementAnalyticsService"))
local AutoclickerAnalyticsService = require(Services:WaitForChild("AutoclickerAnalyticsService"))
local FloorAnalyticsService = require(Services:WaitForChild("FloorAnalyticsService"))
local FloorService = require(Services:WaitForChild("FloorService"))

-- Apply the PVP pause (hide StarterPack weapons) before any player spawns.
PvpService.Init()
DevTuningService.Init()
PlacementAnalyticsService.Init()
AutoclickerAnalyticsService.Init()
FloorAnalyticsService.Init()

PlayerDataService.Init()
SheetService.Init()
FloorService.Init()
CookieService.Init()
ShieldService.Init()
UpgradeService.Init()
ProductionService.Init()
AutoclickService.Init()
ResetStatsService.Init()
GoldenCookieService.Init()
GemService.Init()
WheelService.Init()
DailyRewardService.Init()
OfflineEarningsService.Init()
StoryService.Init()
XpService.Init()
PlayerMetricsService.Init()
SettingsService.Init()
PlayerSetupService.Init()
TestCommandService.Init()
MascotService.Init()
BoostService.Init()
MonetizationService.Init()

print("Cosmic Crumb server started")
