local Config = require(script.Parent.Parent.Parent:WaitForChild("MultiplierHudConfig"))

return {
	feature = "MultiplierHud",
	collapsedByDefault = false,
	tunables = {
		{
			key = "LeftOffset",
			default = Config.LeftOffset,
			kind = "number",
			min = 0,
			max = 200,
			step = 1,
			scope = "client",
			description = "Horizontal offset of the multiplier icon row from the device-safe left edge.",
		},
		{
			key = "BottomOffset",
			default = Config.BottomOffset,
			kind = "number",
			min = 0,
			max = 200,
			step = 1,
			scope = "client",
			description = "Vertical offset of the multiplier icon row from the device-safe bottom edge.",
		},
		{
			key = "SlotGap",
			default = Config.SlotGap,
			kind = "number",
			min = 0,
			max = 32,
			step = 1,
			scope = "client",
			description = "Horizontal spacing between active multiplier icons.",
		},
		{
			key = "DesktopScale",
			default = Config.DesktopScale,
			kind = "number",
			min = 0.5,
			max = 1.5,
			step = 0.05,
			scope = "client",
			description = "Scale of the multiplier icon row on non-compact viewports.",
		},
		{
			key = "CompactScale",
			default = Config.CompactScale,
			kind = "number",
			min = 0.4,
			max = 1.2,
			step = 0.05,
			scope = "client",
			description = "Scale of the multiplier icon row on compact phone viewports.",
		},
		{
			key = "CountdownRefreshSeconds",
			default = Config.CountdownRefreshSeconds,
			kind = "number",
			min = 0.1,
			max = 1,
			step = 0.05,
			scope = "client",
			description = "Client display refresh interval for server-authoritative expiry countdowns.",
		},
		{
			key = "WarningThresholdSeconds",
			default = Config.WarningThresholdSeconds,
			kind = "number",
			min = 0,
			max = 300,
			step = 5,
			scope = "client",
			description = "Remaining duration at which a timed source uses the warning text color.",
		},
		{
			key = "InfinityTextSize",
			default = Config.InfinityTextSize,
			kind = "number",
			min = 8,
			max = 32,
			step = 1,
			scope = "client",
			description = "Text size used by permanent multiplier infinity symbols.",
		},
		{
			key = "CountdownTextSize",
			default = Config.CountdownTextSize,
			kind = "number",
			min = 8,
			max = 32,
			step = 1,
			scope = "client",
			description = "Text size used by timed multiplier countdowns.",
		},
		{
			key = "NormalTextColor",
			default = Config.NormalTextColor,
			kind = "Color3",
			scope = "client",
			description = "Countdown and infinity text color outside the expiry warning window.",
		},
		{
			key = "WarningTextColor",
			default = Config.WarningTextColor,
			kind = "Color3",
			scope = "client",
			description = "Countdown text color inside the expiry warning window.",
		},
		{
			key = "ActivationStartScale",
			default = Config.ActivationStartScale,
			kind = "number",
			min = 0.4,
			max = 1,
			step = 0.02,
			scope = "client",
			description = "Starting scale for a newly activated multiplier icon.",
		},
		{
			key = "ActivationPopScale",
			default = Config.ActivationPopScale,
			kind = "number",
			min = 1,
			max = 1.5,
			step = 0.02,
			scope = "client",
			description = "Peak scale reached by a newly activated multiplier icon.",
		},
		{
			key = "ActivationPopSeconds",
			default = Config.ActivationPopSeconds,
			kind = "number",
			min = 0.05,
			max = 0.6,
			step = 0.01,
			scope = "client",
			description = "Time for a multiplier icon to reach its activation peak.",
		},
		{
			key = "ActivationSettleSeconds",
			default = Config.ActivationSettleSeconds,
			kind = "number",
			min = 0.05,
			max = 0.6,
			step = 0.01,
			scope = "client",
			description = "Time for an activated multiplier icon to settle to normal size.",
		},
		{
			key = "RemovalScale",
			default = Config.RemovalScale,
			kind = "number",
			min = 0.3,
			max = 1,
			step = 0.02,
			scope = "client",
			description = "Final scale of a multiplier icon as it disappears.",
		},
		{
			key = "RemovalSeconds",
			default = Config.RemovalSeconds,
			kind = "number",
			min = 0.05,
			max = 0.6,
			step = 0.01,
			scope = "client",
			description = "Duration of the multiplier icon removal animation.",
		},
		{
			key = "WarningPulseScale",
			default = Config.WarningPulseScale,
			kind = "number",
			min = 1,
			max = 1.3,
			step = 0.01,
			scope = "client",
			description = "Peak scale of the repeating expiry-warning pulse.",
		},
		{
			key = "WarningPulseSeconds",
			default = Config.WarningPulseSeconds,
			kind = "number",
			min = 0.15,
			max = 2,
			step = 0.05,
			scope = "client",
			description = "Time for one half of the expiry-warning pulse.",
		},
	},
}
