return {
	feature = "PlacementControls",
	tunables = {
		{
			key = "SlotSizePixels",
			default = 72,
			kind = "number",
			min = 56,
			max = 88,
			step = 2,
			scope = "client",
			description = "Equal unscaled pixel size of each hotbar action slot during placement.",
		},
		{
			key = "SlotGapPixels",
			default = 8,
			kind = "number",
			min = 4,
			max = 20,
			step = 2,
			scope = "client",
			description = "Unscaled horizontal gap between placement action slots.",
		},
		{
			key = "TransitionSeconds",
			default = 0.25,
			kind = "number",
			min = 0,
			max = 0.5,
			step = 0.02,
			scope = "client",
			description = "Shared time for the hotbar to enter and leave its equal-size placement pose.",
		},
		{
			key = "MultiPlaceStateTransitionSeconds",
			default = 0.2,
			kind = "number",
			min = 0,
			max = 0.5,
			step = 0.02,
			scope = "client",
			description = "Time for the classic PC Multi Place button to change from cancel to done.",
		},
		{
			key = "MultiPlaceCounterOffsetX",
			default = 18,
			kind = "number",
			min = 4,
			max = 48,
			step = 1,
			scope = "client",
			description = "Horizontal pixel offset of the Multi Place run counter from the cursor.",
		},
		{
			key = "MultiPlaceCounterOffsetY",
			default = 18,
			kind = "number",
			min = 4,
			max = 48,
			step = 1,
			scope = "client",
			description = "Vertical pixel offset of the Multi Place run counter from the cursor.",
		},
	},
}
