-- Provisional presentation and world-reveal tuning for vertical floors. Bake approved
-- values into final config and remove this registry when the user's visual pass is final.
local FloorConfig = require(script.Parent.Parent.Parent:WaitForChild("FloorConfig"))
local REVEAL_DEFAULTS = FloorConfig.Reveal

local EASING_STYLES = {
	Enum.EasingStyle.Quad,
	Enum.EasingStyle.Cubic,
	Enum.EasingStyle.Quart,
	Enum.EasingStyle.Quint,
	Enum.EasingStyle.Back,
}

return {
	feature = "VerticalFloors",
	collapsedByDefault = true,
	tunables = {
		{
			key = "FloorStartHeight",
			default = REVEAL_DEFAULTS.FloorStartHeight,
			kind = "number",
			min = -80,
			max = 80,
			step = 1,
			scope = "server",
			description = "Signed vertical start offset; negative values make the floor rise into place.",
		},
		{
			key = "FloorStartRadialOffset",
			default = REVEAL_DEFAULTS.FloorStartRadialOffset,
			kind = "number",
			min = -80,
			max = 80,
			step = 1,
			scope = "server",
			description = "Signed radial start offset; positive starts inward and negative starts outward.",
		},
		{
			key = "GateSlideDistance",
			default = REVEAL_DEFAULTS.GateSlideDistance,
			kind = "number",
			min = -134,
			max = 134,
			step = 1,
			scope = "server",
			description = "Signed sideways crater-gate travel; negative reverses each half's direction.",
		},
		{
			key = "FloorRevealDuration",
			default = REVEAL_DEFAULTS.FloorRevealDuration,
			kind = "number",
			min = 0.1,
			max = 5,
			step = 0.05,
			scope = "server",
			description = "Duration of the floor-parts track while revealing.",
		},
		{
			key = "FloorRelockDuration",
			default = REVEAL_DEFAULTS.FloorRelockDuration,
			kind = "number",
			min = 0.1,
			max = 5,
			step = 0.05,
			scope = "server",
			description = "Duration of the floor-parts track while returning to locked.",
		},
		{
			key = "FloorEasingStyle",
			default = REVEAL_DEFAULTS.FloorEasingStyle,
			kind = "enum",
			options = EASING_STYLES,
			scope = "server",
			description = "Easing curve used only by the moving floor parts.",
		},
		{
			key = "GateRevealDuration",
			default = REVEAL_DEFAULTS.GateRevealDuration,
			kind = "number",
			min = 0.1,
			max = 5,
			step = 0.05,
			scope = "server",
			description = "Duration of the crater-gate track while opening.",
		},
		{
			key = "GateRelockDuration",
			default = REVEAL_DEFAULTS.GateRelockDuration,
			kind = "number",
			min = 0.1,
			max = 5,
			step = 0.05,
			scope = "server",
			description = "Duration of the crater-gate track while closing.",
		},
		{
			key = "GateEasingStyle",
			default = REVEAL_DEFAULTS.GateEasingStyle,
			kind = "enum",
			options = EASING_STYLES,
			scope = "server",
			description = "Easing curve used only by the sliding crater gates.",
		},
		{
			key = "GroundGridColor",
			default = Color3.fromRGB(120, 210, 255),
			kind = "Color3",
			scope = "client",
			description = "Placement-grid line color on the Ground floor.",
		},
		{
			key = "IndustryGridColor",
			default = Color3.fromRGB(255, 159, 67),
			kind = "Color3",
			scope = "client",
			description = "Placement-grid line color on the Industry floor.",
		},
		{
			key = "PartStagger",
			default = REVEAL_DEFAULTS.PartStagger,
			kind = "number",
			min = 0,
			max = 0.15,
			step = 0.005,
			scope = "server",
			description = "Delay between successive floor parts beginning their landing tween.",
		},
		{
			key = "PreviewFloorOrder",
			default = 1,
			kind = "number",
			min = 1,
			max = 3,
			step = 1,
			scope = "server",
			description = "Dev-only floor number controlled by PreviewReveal; saved progression is unchanged.",
		},
		{
			key = "PreviewReveal",
			default = false,
			kind = "boolean",
			scope = "server",
			description = "Dev-only: ON reveals the selected floor; OFF tweens it back to the locked pose.",
		},
		{
			key = "SequenceGap",
			default = REVEAL_DEFAULTS.SequenceGap,
			kind = "number",
			min = -3,
			max = 3,
			step = 0.05,
			scope = "server",
			description = "Signed gap between tracks: positive opens gate first/relocks floor first; negative reverses it.",
		},
		{
			key = "FinanceGridColor",
			default = Color3.fromRGB(55, 200, 175),
			kind = "Color3",
			scope = "client",
			description = "Placement-grid line color on the Finance and Distribution floor.",
		},
		{
			key = "ScienceGridColor",
			default = Color3.fromRGB(182, 117, 255),
			kind = "Color3",
			scope = "client",
			description = "Placement-grid line color on the Science floor.",
		},
	},
}
